#!/bin/bash
# Deploy to Cloudflare Pages

echo "=== Cloudflare Pages Deployment ==="
echo ""
echo "1. First, login to Cloudflare:"
echo "   npx wrangler login"
echo ""
echo "2. Create D1 database:"
echo "   npx wrangler d1 create chepseon-sms-db"
echo "   (Copy the database_id to wrangler.toml)"
echo ""
echo "3. Update wrangler.toml with the database_id"
echo ""
echo "4. Run D1 schema:"
echo "   npx wrangler d1 execute chepseon-sms-db --file=./d1-schema.sql"
echo ""
echo "5. Deploy to Cloudflare Pages:"
echo "   npx wrangler pages deploy .vercel/output/static --project-name=chepseon-next"
echo ""
echo "Or connect GitHub repo in Cloudflare Pages dashboard for auto-deploy!"
